import Head from 'next/head'

// @ts-ignore
import Notification from '@webjet/react/components/notification' 
// @ts-ignore
import Accordion from '@webjet/react/components/accordion';
// @ts-ignore
import IconGuestServices from '@webjet/react-icons/guest-services';
// @ts-ignore
import IconFood from '@webjet/react-icons/food';
// @ts-ignore
import IconParking from '@webjet/react-icons/parking';

// @ts-ignore
import Select from '@webjet/react/components/select'

const optionList = [
  { value: 'Economy', label: 'Economy' },
  { value: 'Premium', label: 'Premium Economy', isDisabled: true },
  { value: 'Business', label: 'Business' },
  { value: 'First', label: 'First' }
]

export default function Home () {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700&display=swap" rel="stylesheet" />
      </Head>
      <main>
        <h2>Notification</h2>
        <Notification type='success' prominence='high'>
          <h3>This is the heading for the notification.</h3>
          This is the body text that is used within a notification.
        </Notification>
        <br />
        <Notification type='info' prominence='high'>
          <h3>This is the heading for the notification.</h3>
          This is the body text that is used within a notification.
        </Notification>

        <h2>Accordion</h2>
        <Accordion heading='Guest services' icon={IconGuestServices} headingBgColor='#FFFFFF' arrowType='arrow' isExpanded={false}>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit aliquam feugiat
        </Accordion>
        <Accordion heading='Food & Drink' icon={IconFood} headingBgColor='#FFFFFF' arrowType='arrow' isExpanded={false}>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit aliquam feugiat
        </Accordion>
        <Accordion heading='Parking & Transport' icon={IconParking} headingBgColor='#FFFFFF' arrowType='arrow' isExpanded={false}>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit aliquam feugiat
        </Accordion>


          {/* <Select
            placeholder='Please select one'
            options={optionList}
            portalTarget={false}
            gaProps={{ event: 'select-interaction' }}
            name='fare-types'
          /> */}
      </main>
    </>
  )
}
